Multitask-Unified-Suite-for-Expts/M-USE

USE_CORE/Assets/_Scripts/GeneralScripts/PHP Scripts/copyFolder.php
USE_CORE/Assets/_Scripts/GeneralScripts/PHP Scripts/createFile.php
USE_CORE/Assets/_Scripts/GeneralScripts/PHP Scripts/createFolder.php
USE_CORE/Assets/_Scripts/GeneralScripts/PHP Scripts/getFile.php
USE_CORE/Assets/_Scripts/GeneralScripts/PHP Scripts/getFilePath.php
USE_CORE/Assets/_Scripts/GeneralScripts/PHP Scripts/getFolderNames.php
USE_CORE/Assets/_Scripts/GeneralScripts/PHP Scripts/testConnection.php
USE_CORE/Assets/_Scripts/GeneralScripts/PHP Scripts/updateFile.php
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/ServerManager.cs

I added the PHP scripts used for the server into the Assets/Scripts/GeneralScripts/PHP Scripts folder, so that people have access to the scripts to place on their server.

Added PHP Scripts to Project

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/Resources/Penguin.gltf.meta
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/Resources/Penguin.gltf.prefab.meta

Removed the FileStringContainsTabs method that was unused.

Removed unused FileStringContainsTabs method

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/TouchFBController/TouchFBController.cs
USE_CORE/Assets/_USE_Session/_TaskSelection.unity
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

1) At end of each task, i've unsubscribed the TouchFbController from the event. 2) Fixed CR's PlayerViewPanel text.
3) Updated each task's PlayerViewPanel section to do gameObject.AddComponent instead of instantiating, since it inherits from monobehavior and should be added as a component.

Unsubscribed TouchFB at end of task

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs

Adjusted token sizing for CR's mac build, and adjusted token sizing for EC's mac build.

Mac build sizing work.

---

USE_CORE/Assets/Prefabs/Resources/LoadingCanvas.prefab
USE_CORE/Assets/_Scripts/GeneralScripts/LoadingController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/InitScreen_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_USE_Session/_TaskSelection.unity
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/Resources/Materials/New Material.mat

Updates loading controller script and loading circle animation. Updated CR border method.

LoadingController update

---

USE_CORE/Assets/GLTFUtility-master/Plugins/draco/GLTFUtilityDracoLoader.cs

Updated DracoLoader.cs to try and resolve web build issue.

Update to DracoLoader.cs

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/USE_Data.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Settings Management/ImportSettings_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/StimulusHandling/USE_StimulusManagement.cs
USE_CORE/Assets/_USE_Session/NewShaderVariants_Asset.shadervariants
USE_CORE/Assets/_USE_Session/NewShaderVariants_Asset.shadervariants.meta
USE_CORE/ProjectSettings/GraphicsSettings.asset

GLTF Updates

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/SetupSession_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/SetupTask_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/USE_Data.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/USE_ExperimentTemplate_Data.cs
USE_CORE/Packages/packages-lock.json

Removed individual StoreData fields from datacontrollers and instead reference SessionValues.StoreData

StoreData updates

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs

Updated background music method, fixing the null error.

Fixed Background Music

---

USE_CORE/Assets/_Scripts/GeneralScripts/BackgroundMusicController.cs
USE_CORE/Assets/_Scripts/GeneralScripts/BackgroundMusicController.cs.meta
USE_CORE/Assets/_Scripts/GeneralScripts/SessionValues.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_USE_Session/_TaskSelection.unity
USE_CORE/ProjectSettings/ProjectSettings.asset

Fully implemented BackgroundMusicController that communicates with Session

BackgroundMusicController

---

USE_CORE/Assets/Prefabs/Resources/BlockResults.prefab
USE_CORE/Assets/Prefabs/Resources/HumanStartPanel.prefab
USE_CORE/Assets/Prefabs/Resources/HumanVersionToggleButton.prefab
USE_CORE/Assets/Prefabs/Resources/InitScreen_GO.prefab
USE_CORE/Assets/_Scripts/GeneralScripts/ButtonHoverEffect.cs
USE_CORE/Assets/_Scripts/GeneralScripts/ButtonHoverEffect.cs.meta
USE_CORE/Assets/_Scripts/GeneralScripts/HoverEffect.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_UI.cs
USE_CORE/Assets/_USE_Session/_TaskSelection.unity
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition.unity
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/Resources/Materials/GreyBorderMaterial.mat
USE_CORE/Assets/_USE_Tasks/MazeGame/Resources/Materials/New Material.mat

Created the button hover effect class to make font darker when hovered over. Also removed the scaling from certain buttons. Updated GreyBorder material for CR. Updated BlockResults prefab

Button Hover Effect class

---

USE_CORE/Assets/_Scripts/GeneralScripts/FullScreenController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_UI.cs

Pushing small changes before the merge.

Small changes before merging with Seema

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/InitScreen_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/ExperimenterDisplay/HotKeyPanel.cs
USE_CORE/Assets/_USE_Session/_TaskSelection.unity
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs

Moved Call to staircase method to first trial state to fix timing issue with CR.

Fixed Staircase TCIB Bug

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_UI.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/Resources/Materials/New Material.mat
USE_CORE/ProjectSettings/EditorBuildSettings.asset

Added ability for CR's DisplayResults duration to be 0 so that it can be skipped.

CR DisplayResults

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Initialization Screen/LocateFile/StandaloneFileBrowser.meta
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/THR_DefaultConfigs/THR_BlockDef_array.txt
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/THR_DefaultConfigs/THR_ConfigUiDetails_json.json
USE_CORE/Assets/_USE_Tasks/MazeGame/Resources/Materials/New Material.mat

Small THR config updates

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/USE_ExperimentTemplate_Data.cs
USE_CORE/Assets/_USE_Tasks/THR/THR_TrialLevel.cs

Removed the duplicate sessionSettings folder being generated and updated its name. Also fixed a frame data null reference error.

Fixed a Frame Data Null Ref error and SessionSettings duplicate folder

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/SliderFBController/SliderFBController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention.unity
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_Namespace.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_Namespace.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/ProjectSettings/EditorBuildSettings.asset

Started implementing a slider for Sustained Attention.

Start of slider implementation in SA

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/HaloFBController.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Implemented selecting a object, and pausing an object from moving while its being selected.

SA selection work

---

USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition.unity
USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Small changes to SA script and CR's directional light.

SA Small changes

---

USE_CORE/Assets/_Scripts/GeneralScripts/CameraSyncController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/SliderFBController/SliderFBController.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_Namespace.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs
USE_CORE/ProjectSettings/TimelineSettings.asset

Started getting slider to work for SA and also moved the camera logic into FixedUpdate.

SA Updates and Camera method moved to FixedUpdate

---

USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/AntiSaccade_DefaultConfigs/AntiSaccade_TaskDef_singleType.txt
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade.unity
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_Namespace.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Updated AS Camera FOV and positions. Fixed null ref errors in frame data for CR and WWW.

AS, CR, SA

---

USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Added TrialsCompleted and TokenBarCompletions to Sustained Attentions Data.

SA Start of Data Implementation

---

USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention.unity
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Removed Tokenbar and replaced with Slider for Sustained Attention task.

SA Slider Implementation

---

USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Sustained Attention - Added functionality for one selection per interval, and pausing while being selected to only occur for the first selection attempt.

SA Pausing Implementation

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/ServerManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_Namespace.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Added AngleProbabilities variable to Sustained Attention.

SA - Angle Probabilities

---

USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

First attempt at Cycle Implementation for Sustained Attention.

Sustained Attention - Cycle Implementation

---

USE_CORE/Assets/_USE_Tasks/SustainedAttention/ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Fix for the interval issue for Sustained Attention.

SA Interval Fix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/StimulusHandling/USE_StimulusManagement.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_Namespace.cs

Removed UnloadUnusedAssets from USE_StimManagement

Resources UnloadUnusedAssets removed

---

USE_CORE/Assets/_USE_Tasks/SustainedAttention/SA_ObjectManager.cs

Implemented configurable colors for each SA Object.

SA Object Colors Implementation

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SA_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

For Sustained Attention, fixed the objects being destroyed and implemented slider change for each object. Also fixed the BlockResults bug that was only removing the blockResults if it was human.

SA Slider and destroying object fixes. BlockResults bug fix.

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/SliderFBController/SliderFBController.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FloorManager.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/Resources/Prefabs/Tile.prefab
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SA_ObjectManager.cs

Implemented configurable Angle ranges for Sustained Attention task.

SA - Angle Ranges Implementation

---

USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner.unity
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_Namespace.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/ProjectSettings/EditorBuildSettings.asset

Added FruitRunner into the suite.

FruitRunner Initial implementation into the Suite

---

USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Used LINQ to load the SA Config Values instead of accessing the first custom setting.

SA - Custom Settings Fix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/HaloFBController.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_Namespace.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SA_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Fixed the frame data header bug for each individual object.

SA - Frame Data for Objects

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/VerifyTask_Level.cs
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/SustainedAttention_DefaultConfigs/SustainedAttention_BlockDef_array.txt
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/SustainedAttention_DefaultConfigs/SustainedAttention_EventCodeConfig_json.json
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/SustainedAttention_DefaultConfigs/SustainedAttention_TrialDef_array.txt
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SA_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Default configs for Sustained Attention task. Also added an event code for "Object Animation Occured".

SA - Implemented Default Configs for Sustained Attention

---

USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/MovementCirclesController.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/PlayerMovement.cs

Humans can now control the movement via keyboard arrows in addition to using the movement circles.

FR - Human Input implementation

---

USE_CORE/Assets/Prefabs/Resources/InitScreen_GO.prefab
USE_CORE/Assets/_Scripts/GeneralScripts/InputFieldManager.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Initialization Screen/LocateFile/FileItem.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/SustainedAttention_DefaultConfigs/SustainedAttention_BlockDef_array.txt
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/SustainedAttention_DefaultConfigs/SustainedAttention_ObjectsDef_array.txt
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/SustainedAttention_DefaultConfigs/SustainedAttention_TrialDef_array.txt
USE_CORE/Assets/_USE_Tasks/FruitRunner/Elipsoid.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner.unity
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/ItemSpawner.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SA_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs

Fixed the touch feedback for SA and added unpause functionality

SA - Touch Fb Fix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Initialization Screen/LocateFile/FileItem.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SA_ObjectManager.cs

For Sustained Attention, while the user is selecting the object, i've incremented the current cycle's start time so that the animations dont loop over each other during selection.

SA - Increased Cycle Time when Selected

---

USE_CORE/Assets/_USE_Tasks/FruitRunner/FloorManager.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_Namespace.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/Item.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/ItemSpawner.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/MovementCirclesController.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/PlayerMovement.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/Resources/Prefabs/Blockade_Left.prefab
USE_CORE/Assets/_USE_Tasks/FruitRunner/Resources/Prefabs/Blockade_Right.prefab

Moved the player's onTriggerEnter method from the Playermovement class to the Item classes. Added sad animation to QuaddleItems OnTriggerEnter. Updated blockade prefabs.

FR - Player OnTriggerEnter

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Settings Management/ImportSettings_Level.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FloorManager.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_Namespace.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/Item.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/ItemSpawner.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/PlayerMovement.cs

Added ability to import string arrays into settings. Also made FR's tile scale and movement speed variables configurable.

FR - Added String array importing

---

USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_Namespace.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs

Removed trialStimFeedbackType from trial def and instead calculate it based off the stim token reward mag.

FR - Quaddle Feedback Type

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/HaloFBController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/NegativeHaloLight.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/PositiveHaloLight.prefab
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FeatureUncertaintyWM/FeatureUncertaintyWM_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

WWW halo changes working on with seema

NT - WWW halo

---

USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_Namespace.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs

Implemented the recency interference variable for the Continuous Recognition Task.

CR - Recency Interference

---

USE_CORE/Assets/_USE_Tasks/FruitRunner/FR_Item.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FR_ItemSpawner.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_Namespace.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs

Finished implementing the banana option for FlexRunner

NT - FlexRunner Banana implementation

---

USE_CORE/Assets/_USE_Tasks/FruitRunner/CameraIntroMovement.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FR_EventManager.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FR_FloorManager.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FR_Item.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FR_ItemManager.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FR_ItemManager.cs.meta
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs

Started implementing Data for FruitRunner.

FR Data Implementation

---

USE_CORE/Assets/_USE_Tasks/FruitRunner/FR_EventManager.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FR_PlayerManager.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs

Implemented event codes for player shifting

NT - Player Shifting Event codes

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/EffortControl_DefaultConfigs/EffortControl_TaskDef_singleType.txt
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/FlexLearning_DefaultConfigs/FlexLearning_TaskDef_singleType.txt

Implemented a task variable called Task Directional Light Intensity to allow experimenters to specify the light intensity in the task def.

Task Directional Light Intensity

---

USE_CORE/Assets/Prefabs/Resources/NewTitleText.prefab
USE_CORE/Assets/Prefabs/Resources/NewTitleText.prefab.meta
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/InitScreen_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs

Added quaddle images to init screen

Init Screen Quaddles

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/InitScreen_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Session/_TaskSelection.unity

updated the starfield to be included in init screen and changed initscreen canvas sorting order to push it behind everything.

starfield update

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/NegativeHaloLight.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/ParticleHaloPositive.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/PositiveHaloLight.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/TokenFBController/TokenFBController.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs

Added a tokenbarfilled event to tokenfbcontroller class and implemented the GiveReward method for FruitRunner

Tokenbar Filled Event & FR GiveReward

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/TokenFBController/TokenFBController.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FeatureUncertaintyWM/FeatureUncertaintyWM_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

Created the tokenbar filled event and implemented for each task.

TokenBar Filled Event Implementation

---

USE_CORE/Assets/Prefabs/Resources/NewTitleText.prefab
USE_CORE/Assets/Prefabs/Resources/QuaddleAnimatorController.controller
USE_CORE/Assets/Prefabs/Resources/QuaddleAnimatorController.controller.meta
USE_CORE/Assets/Prefabs/Resources/QuaddleFadeIn.anim
USE_CORE/Assets/Prefabs/Resources/QuaddleFadeIn.anim.meta
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/InitScreen_Level.cs

Quaddle fade in animation for the images on init screen

NT - Quaddle Fade In Animation

---

USE_CORE/Assets/_USE_Tasks/FruitRunner/SpawnHalfCircle.cs

Updated the spawn half circle method to account for default stim differences

NT - Spawn Half Circle Update

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs

Fixed the task buttons grid bug in the session level.

NT - TaskButtonsGrid Fix

---

USE_CORE/Assets/Prefabs/Resources/Timer.prefab
USE_CORE/Assets/_Scripts/GeneralScripts/Timer.cs
USE_CORE/Assets/_Scripts/GeneralScripts/Timer.cs.meta
USE_CORE/Assets/_Scripts/GeneralScripts/TimerController.cs
USE_CORE/Assets/_Scripts/GeneralScripts/TimerController.cs.meta
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/HaloFBController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_UI.cs
USE_CORE/Assets/_USE_Session/_TaskSelection.unity
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual.unity
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition.unity
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs

Created the TImer and TimerController classes to allow human versions to have timers across all tasks. Implemented in CR and AV so far.

Timer and TimerController classes.

---

USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/SessionConfig_singleType.txt

Removed AV from default session config.

Removed AV from Default Configs

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs

Fixed the no cameras rendering bug on web build

Web Build Fix

---

USE_CORE/Assets/Prefabs/Resources/HumanStartPanel.prefab
USE_CORE/Assets/Prefabs/Resources/USE_Instructions.prefab
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/SustainedAttention/SustainedAttention_TaskLevel.cs

Fixed the blurry instructions text.

Blurry Instructions Text Fix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_UI.cs

Fixed the unclickable start button bug by adding a recursive method to the declaration of the start button children.

NT_UnclickableStartButtonBug

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/StimulusHandling/USE_StimulusManagement.cs

Updated the LoadStims method to try and fix the invalid operation execution.

NT_NewLoadStimsMethod

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs

Update to HandleLoadingStims method, to fix invalid operation execution

Potential fix for handleLoadingStims method

---

USE_CORE/Assets/Prefabs/Resources/TitleText.prefab

Fixed the M of title text, making it orange again.

Update TitleText color

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/InitScreen_Level.cs

Moved audo clips from init screen level now that handled by the SessionAudioController class.

Removed audio from init screen

---

USE_CORE/Assets/Prefabs/Resources/InitScreen_GO.prefab
USE_CORE/Assets/Prefabs/Resources/SessionSummary.prefab
USE_CORE/Assets/Prefabs/Resources/SessionSummary_GridItem.prefab
USE_CORE/Assets/Prefabs/Resources/TaskResults_GridItem.prefab
USE_CORE/Assets/Prefabs/Resources/TitleText.prefab
USE_CORE/Assets/_Scripts/GeneralScripts/SessionSummaryController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs

Updated the UI for the Session Summary and Task Results prefabs.

UI Changes - Session Summary

---

USE_CORE/Assets/Prefabs/Resources/TaskResults_GridItem.prefab
USE_CORE/Assets/_Scripts/GeneralScripts/SessionSummaryController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs

Edited the task results prefab and removed the camera rotation code now that main camera is 0 rotation.

UI Changes - Task Results prefab & camera rotation

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/StimulusHandling/USE_StimulusManagement.cs

Implemented the task resources folder loading of stimuli for local.

Task Resources Folder - Local Implementation

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/ExperimenterDisplay/Resources/Queue_GridItem.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/ExperimenterDisplay/Resources/TaskOrder_GridItem.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/ExperimenterDisplay/Resources/Tasks_GridItem.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/StimulusHandling/StimDefPointer.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/StimulusHandling/USE_StimulusManagement.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_SequenceManager.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Updated the DefineTrialstims method for WWW and also fixed the individual bold font for each task's summary strings.

NT_WWW_Updates_And_BoldFontTaskFix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs

Updates to Keep Track frame data, implementing open/closed frame data for each object.

NT_KeepTrackFrameData

---

USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs

Updates to KeepTrack including OpenAngle and MouthAngleProbabilities.

KeepTrack Updates

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/CircleHalo.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/HaloFBController.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs

fixed the circle halo class fix for 2D objects, including Keep Track. Also added MouthAngles to framedata.

NT_CircleHaloFix_MouthAngleFrameData

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/SetupTask_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/ServerManager.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/CircleHalo.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/HaloFBController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/ParticleHalo.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/Resources/FeedbackControllers.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/StimulusHandling/USE_StimulusManagement.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/THRQ/THRQ_TrialLevel.cs

Fixed the sub folder searching for stim!

NT_SubFolderSearchFix

---

USE_CORE/Assets/_Scripts/GeneralScripts/MaskController.cs
USE_CORE/Assets/_Scripts/GeneralScripts/MaskController.cs.meta
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/StimulusHandling/USE_StimulusManagement.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_Namespace.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_SequenceManager.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Committing the rest of the masked changes with the WWW implementation commented out while working on it.

NT_RestOfMaskChanges

---

USE_CORE/Assets/_Scripts/GeneralScripts/MaskController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/SetupTask_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Fully implemented the masking controller into WWW.

NT_MaskImplementation_WWW

---

USE_CORE/Assets/_Scripts/GeneralScripts/MaskController.cs
USE_CORE/Assets/_Scripts/GeneralScripts/SessionBuilder.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_Namespace.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_SequenceManager.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Mask Controller updates and also fixed the Task Icons bug that wasn't getting the correct queue order on the experimenter display.

NT_MaskController_TaskIconsBugFix

---

USE_CORE/Assets/_Scripts/GeneralScripts/MaskController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs

Fixed the backup context search issue.

NT_ContextPathFix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TaskLevel.cs

Added debug statements for kiosk debugging with adam.

NT_KioskDebugStatements

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Initialization Screen/LocateFile/LocateFile.cs

NT_MoreDebugs

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Initialization Screen/LocateFile/LocateFile.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TaskLevel.cs

Figured out the kiosk bug (hidden block def) and removed all debugs.

NT_KioskBugFixed

---

USE_CORE/Assets/_Scripts/GeneralScripts/MaskController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/CircleHalo.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/HaloFBController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/ParticleHalo.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Initialization Screen/LocateFile/LocateFile.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_Namespace.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

Starting implementation of electrostimulation after specified time.

NT_StimulationStart

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs

Implemented the RunSimulation option for KeepTrack.

NT_KeepTrackRunSimulation

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/ExperimenterDisplay/Resources/Queue_GridItem.prefab
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/KeepTrack_DefaultConfigs/KeepTrack_BlockDef_array.txt
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/KeepTrack_DefaultConfigs/KeepTrack_ObjectsDef_array.txt
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/KeepTrack_DefaultConfigs/KeepTrack_TrialDef_array.txt
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_Namespace.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs

Implemented configurable starting positions at the trial level for Keep Track. Also updated the default configs.

NT_KeepTrackStartingPositions

---

USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/KeepTrack_DefaultConfigs/KeepTrack_ObjectsDef_array.txt
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/KeepTrack_DefaultConfigs/KeepTrack_TrialDef_array.txt
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_Namespace.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs

Moved the configurability of object starting positions to the Object config instead of the Trial config

NT_KeepTrackObjStartingPos

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/StimulusHandling/USE_StimulusManagement.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Updated the WWW trial level to accomodate new stim location randomization process discussed with Xuan.

NT_WWW_StimLocations

---

USE_CORE/Assets/_Scripts/GeneralScripts/MaskController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/LogWriter.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/ExperimenterDisplay/HotKeyPanel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_SequenceManager.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Fixed the masking and sequencing for WhatWhenWhere.

NT_MaskFixForWWW

---

USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs

CR Stimulation update and FL update.

NT_StimulationCR

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/ApplicationQuit.cs

Worked through ensuring when the application quits the data is saved. If its the end of the session the savedata state will show otherwise it will just quit.

NT_SaveDataApplicationFix

---

USE_CORE/Assets/_Scripts/GeneralScripts/MaskController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/WhatWhenWhere_DefaultConfigs/WhatWhenWhere_BlockDef_array.txt
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_Namespace.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_Namespace.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_Namespace.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_SequenceManager.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

For masking i've added the configurability of mask color, and the ability to fade in the mask over a specified/configurable duration. For stimulation I finalized the implementation into CR and FL.

NT_StimulationAndMasking

---

USE_CORE/Assets/_Scripts/GeneralScripts/MaskController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/USE_ExperimentTemplate_Data.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs

Fixed the  null error caused by mask being destroyed before full animation duration.

NT_MaskRendererFix

---

USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Fixed the null error for stimulation for CR, and updated makestimfaceCamera methods.

NT_StimulationFixAndFaceCamera

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_Namespace.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs

Implemented new Stimulation changes into CR and FL.

NT_StimulationBigChanges

---

USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TaskLevel.cs

Updated CR task level for stimulation so that it shows up on UI of experimenter display

NT_CrTaskLevelStimulationUpdate

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_SequenceManager.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Fixed the masking bug that was incorrectly incrementing numCorrectChoices every time they selected a correct stim, even if already selected!

NT_MaskingFix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/EyeTracker/TobiiEyeTrackerController.cs

004_Changes

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs

Added OngoingSelection duration for debugging purposes in kiosk

NT_DebugsForKioskStimulation

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/USE_ExperimentTemplate_Data.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/EventCodeManager.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/THR/THR_TrialLevel.cs

Changes to EventCodeManager class removing calls to SentCodeImmediate so only ReferenceEventCodes remain in that column.

NT_InitialEventCodeManager changes

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/EventCodeManager.cs
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/SessionEventCodeConfig_json.json
USE_CORE/Assets/_USE_Session/_TaskSelection.unity
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs

Updated default event code config

NT_DefaultEventCodeConfig

---

USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs

Fixed the null error for flex learning

NT_FixforFlexLearningStimulation

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/USE_ExperimentTemplate_Data.cs

Removed ref event code from frame data

NT_RemovedRefCode

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/USE_ExperimentTemplate_Data.cs

Removed the string joining of frame event codes.

NT_RemovedStringJoiningOfFrameCodes

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/USE_ExperimentTemplate_Data.cs

`Fixed the bug for frame event code frame data column.

NT_FrameEventCodeDataFix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/EventCodeManager.cs

Working with frame event codes being sent in subsequent frames. About to try sending all at once.

NT_FullyWorkingWithSubsequentFrameEventCodes

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/SetupSession_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/SyncBoxController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs

Updated keep track for reward pulse changes and updated stimulation config moving to session.

NT_KeepTrackUpdatesAndStimulationConfigChanges

---

USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/KeepTrack_DefaultConfigs/KeepTrack_ObjectsDef_array.txt
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs

Updated default config of KeepTrack to have new reward pulse by second variable

NT_KeepTrackDefaultConfigUpdate

---

USE_CORE/Assets/_USE_Session/Resources/DefaultResources/AudioClips 2.meta
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/SessionEventCodeConfig_json.json

Updated default config event code file

NT_DefaultEventCodeUpdate

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/EventCodeManager.cs

Increased the ref event code range to 255

NT_EventCodeRangeIncreased

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/EventCodeManager.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs

began updating calls to event code manager class from individual task scripts

NT_UpdatingCalls

---

USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs

Added debug to Keep Track trial level for keely

NT_KeepTrackDebugging

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs

Removed the debug log that was breaking local version

NT_RemovedRandomDebugLog

---

USE_CORE/Assets/_USE_Session/_TaskSelection.unity
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs

Fixed the color issue for keep track so keely can use normal RGB values now!

NT_KeepTrackColorFix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/EventCodeManager.cs

fixed the N hotkey button with a null check for gaze controller

NT_NhotKeyButtonFix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_Namespace.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KT_ObjectManager.cs

Implemented new Probabilistic stim token reward, AND tried to fix the keely objects not dissapearing bug.

NT_ProbStimTokenReward

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs

Added ongoing selection to trial level template and added it's duration to CR's experimenter display to show experimenter.

NT_OngoingSelectionDurations

---

USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs

small update to ongoing selection work to format it correctly and set it null before choostStim state.

NT_OngoingSelectionUpdate

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/CircleHalo.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/HaloFBController/HaloFBController.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibrationController.cs
USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs

NT_HaloStuff

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/Session.cs

Fixed the null errors for clearStimLists

NT_ClearStimListsFix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs

Fixed null gaze calibration controller

NT_GazeCalibNullFix

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

Moved DetermineCollectDataStatus to update method and removed delay state.

NT_GazeTrialLevelUpdate

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/THR/THR_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

NT_OngoingSelectionCounter

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

removing TurnOffCalibration from ITI as it broke build.

NT_GazeUpdates

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Session.cs

Calibration updates for kiosk debugging

NT_GazeUpdatesCalib

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_Namespace.cs
USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

Added shrinking during check and calibrate states and added confirmduration configurable variable.

NT_Gaze_MoreShrinking_ConfirmDuration

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/EyeTracker/GazeTracker.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/EyeTracker/TobiiEyeTrackerController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

- removed invalid gaze update error trigger
- added code to have the calibration point shrink during calibration

Corrected Shrinking Calibration Fix, Updated Gaze Shotgun Error Triggers

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs

Updated WriteDataFiles call in trial level.

NT_DataWritingFix

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_Namespace.cs

lowered the confirm duration default value for gaze

NT_LoweredConfirmDuration

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

Implemented ongoing selection duration on experimenter display for gaze

NT_Gaze_OngoingSelection

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

NT_OngoingSelChange

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

NT_GazeStrings

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

NT_Gazestring

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

updated ongoing selection string to TimeInCalibRange

NT_TimeInCalibRange

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

removed ongoing selection from gaze trial level

NT_removedOngoingSel

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

Removed unused variables and using directives  in gaze trial level

NT_RemovedUnusedGazeTrialVariables

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

added back the originalScale variable

NT_AddBackOriginalScale

---

USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs

Added gaze and touch shotgun to AudioVisual and EffortControl tasks.

NT_TouchShotgun

---

USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs

Fixed the ongoing selection duration not showing up for FL!

NT_OngoingSelDurFix_FL

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

Updated the TimeInCalibRange string.

NT_StringUpdate

---

USE_CORE/Assets/_Scripts/GeneralScripts/InputFieldManager.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Data Management/ServerManager.cs

Made it so that you can now copy and paste the server url onto the init screen.

NT_CopyPasteServerURL

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

more attempts to try and fix reward issue for gaze

NT_RewardFixes

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

NT_GazeDebug

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

fix for no reward structure being read in

NT_GazeRewardStructureFIx

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

optimized shouldgivereward method

NT_GazeReward

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

Updates to TurnOnCalibration() method to add null checks and debug logs for kiosk debugging tomorrow.

NT_TurnOnCalibrationMethod

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

trying to fix the turnOnCalibration error

NT_GazeFixes

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

removed call to turnOnCalib from setupTrial

NT_RemovedTurnOnCalibCall

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_Namespace.cs

added a default value for RewardStructure

NT_RewardStructure

---

USE_CORE/Assets/Prefabs/Resources/HumanStartPanel.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_Namespace.cs
USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

1) CorrectChoices data and PercentageRewarded data, 2) Fixed the start button background raycast bug

NT_FL_Data

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/InputBroker.cs

added dynamic shotgun rays for raycasting

NT_DynamicShotgunRays

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_Namespace.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

Updated each tasks selection handler to use gaze shotgun and touch shotgun. Started implementing stimulation for WWW. Updated coroutine call to syncbox reward methods in each task.

NT_SelectionHandler_WWWstartedStimulation

---

USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs

Check if in correct objects list before failing choice, since they could click something outside

NT_ECCorrectObjects

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs

NoOngoingSelection update for GazeShotgun handler in selectiontracking class.

NT_SelectionUpdates_GazeNoOngoing

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

Updated call to setupselectionhandler in each task to use session config value. Also updated moveTooFar condition.

NT_TaskHandlers

---

USE_CORE/Assets/Prefabs/Resources/StartButton.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs

Fixed the start button selection issues by adding a transparent front circle that's the only selectable gameobject.

NT_StartButtonSelectionFix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs

decreased touch durations and increased maxPixelDisplacement

NT_UpdatedDurations

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/Session.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

added collectsamplepoints back in to test in booth.

NT_GazeDebugging

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

returned old termination criteria.

NT_SmallchangeGaze

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/SetupSession_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/EyeTracker/GazeTracker.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/MouseTracker.cs
USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

testing turning off the mouse tracker for gaze tracking to remove redundant fields in frame data.

NT_TestingTurningOffMouseTracker

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/SetupSession_Level.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/EyeTracker/GazeTracker.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/MouseTracker.cs

update to stop redundant frame data

NT_EnablingTrackers

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/EyeTracker/GazeTracker.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/MouseTracker.cs
USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

NT_TestingRecycledCalibration

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

NT_GazeCalib

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

reverted back to keeping sample available but not using.

NT_GazeTrialReversion

---

USE_CORE/Assets/_USE_Tasks/GazeCalibration/GazeCalibration_TrialLevel.cs

Restartcalibration method and fixed null syncbox and additional termination method in ConfirmResults.

NT_GazeRestartCalib

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/ExperimenterDisplay/Resources/Default_ExperimenterDisplay.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/ExperimenterDisplay/Resources/TaskOrderSection.prefab
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/SyncBoxController.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs

fixed the session stimulationPulses value not matching CR task value. Also updated the experimenter prefab to be poppins.

NT_StimPulsesUpdate

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

Implemented a separate duration for start button selection for all tasks.

NT_StartButtonSelDuration

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/TouchFBController/TouchFBController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/SyncBoxController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FeatureUncertaintyWM/FeatureUncertaintyWM_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/THRQ/THRQ_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/TemporalOrderJudgement/TemporalOrderJudgement_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

Touch feedback size. Debugs for syncbox testing.

NT_TouchFbSize_SyncboxDebugs

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/ExperimenterDisplay/Resources/Default_ExperimenterDisplay.prefab
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

updated exp display sizing and removed extra lines

NT_rewardPulsesDebug

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/SyncBoxController.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

Moved increment to session stimulation pulses to syncboxcontroller method instead of individual tasks.

NT_StimPulsesOutOfTasksIntoSyncbox

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/Ports_Management/SerialPortThreaded.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/SyncBoxController.cs

Added debug to serial port controller

NT_SerialPortDebug

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TaskLevel.cs

Updates to session variables for developer manual.

NT_ManualUpdates

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/FBControllers/TouchFBController/TouchFBController.cs
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/AntiSaccade_DefaultConfigs/AntiSaccade_ConfigUiDetails_json.json
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/ContinuousRecognition_DefaultConfigs/ContinuousRecognition_ConfigUiDetails_json.json
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/EffortControl_DefaultConfigs/EffortControl_ConfigUiDetails_json.json
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/FruitRunner_DefaultConfigs/FruitRunner_ConfigUiDetails_json.json
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/KeepTrack_DefaultConfigs/KeepTrack_ConfigUiDetails_json.json
USE_CORE/Assets/_USE_Session/Resources/DefaultSessionConfigs/SessionEventCodeConfig_json.json
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TrialLevel.cs

1) Updated the default configs for each task so they work. 2) Fixed the maze game touch feedback bug.

NT_DefaultConfigsUpdate_MazeTouchFbFix

---

USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

Uncommented testing section of MazeGame

NT_Uncomment

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/SyncBoxController.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_Namespace.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_Namespace.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Implemented stimulation for WWW

NT_WWW_Stimulation

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/USE_Def_Namespace.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs

Fixed the CR logic issue for stimulation

NT_CR_Fixed

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Task.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/AntiSaccade/AntiSaccade_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/AudioVisual/AudioVisual_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/EffortControl/EffortControl_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/FruitRunner/FruitRunner_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/MazeGame/MazeGame_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/THR/THR_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/THR/THR_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TaskLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TaskLevel.cs

Implemented abstract and override methods for StimulationCoroutine and SetBlockSummaryString. Updated all tasks.

NT_StimulationCoroutine_BlockSummaryString

---

USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TaskLevel.cs

Updated the searchstring for keep track task level to fix bug from testing local configs

NT_KeepTrackObjectsDef

---

USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TaskLevel.cs

removed debug and reverted search string

NT_keepTrack

---

USE_CORE/Assets/_USE_Tasks/KeepTrack/KeepTrack_TaskLevel.cs

Update to custom setting for KeepTrack

NT_CustomSettingUpdate

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Hierarchical Finite State Machine/USE_ExperimentTemplate_Trial.cs
USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs
USE_CORE/Assets/_USE_Tasks/ContinuousRecognition/ContinuousRecognition_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/FlexLearning/FlexLearning_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/VisualSearch/VisualSearch_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WhatWhenWhere/WhatWhenWhere_TrialLevel.cs
USE_CORE/Assets/_USE_Tasks/WorkingMemory/WorkingMemory_TrialLevel.cs

1) Clearing all selections before choosestim,
2) Setting handler inactive as soon as choice made. 3) Removed waiting for touchfeedback to finish (from other stimulation tasks too)

NT_WWWGazeBug

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs

1) Setting currentTarget and OngoingSelection null when resetting selections.

NT_2ndAttemptGazeFix

---

USE_CORE/Assets/_Scripts/M_USE/M_USE Modules/InputHandling/SelectionTracking.cs

Fixed the null ref error relating to last choice being null.

NT_NullErrorFix
